export const productList = [
  {
    id: 1,
    name: "Sunset Bliss",
    image: ["https://picsum.photos/id/30/1280/901"],
    description: "A beautiful sunset over the horizon.",
    price: 49.99,
  },
  {
    id: 2,
    name: "Majestic Mountains",
    image: ["https://picsum.photos/id/31/3264/4912"],
    description: "Scenic view of towering mountains.",
    price: 79.99,
  },
  {
    id: 3,
    name: "Serene Lake",
    image: ["https://picsum.photos/id/32/4032/3024"],
    description: "A tranquil lake in the heart of nature.",
    price: 59.99,
  },
  {
    id: 4,
    name: "Golden Fields",
    image: ["https://picsum.photos/id/33/5000/3333"],
    description: "Endless fields of golden crops.",
    price: 39.99,
  },
  {
    id: 5,
    name: "Urban Exploration",
    image: ["https://picsum.photos/id/34/3872/2592"],
    description: "Exploring the city's streets and buildings.",
    price: 69.99,
  },
  {
    id: 6,
    name: "Coastal Escape",
    image: ["https://picsum.photos/id/35/2758/3622"],
    description: "Relaxing by the sea with crashing waves.",
    price: 54.99,
  },
  {
    id: 7,
    name: "Mystical Forest",
    image: ["https://picsum.photos/id/36/4179/2790"],
    description: "Journeying through a mysterious forest.",
    price: 59.99,
  },
  {
    id: 8,
    name: "City Lights",
    image: ["https://picsum.photos/id/37/2000/1333"],
    description: "The city comes alive with dazzling lights.",
    price: 49.99,
  },
  {
    id: 9,
    name: "Rural Beauty",
    image: ["https://picsum.photos/id/38/1280/960"],
    description: "Exploring the charm of the countryside.",
    price: 44.99,
  },
  {
    id: 10,
    name: "Mountain Retreat",
    image: ["https://picsum.photos/id/39/3456/2304"],
    description: "A peaceful getaway in the mountains.",
    price: 74.99,
  },
  {
    id: 11,
    name: "Ocean Adventure",
    image: ["https://picsum.photos/id/40/4106/2806"],
    description: "Setting sail for an oceanic adventure.",
    price: 89.99,
  },
  {
    id: 12,
    name: "Garden Blooms",
    image: ["https://picsum.photos/id/41/1280/805"],
    description: "Vivid blooms in a lush garden.",
    price: 34.99,
  },
  {
    id: 13,
    name: "Wilderness Expedition",
    image: ["https://picsum.photos/id/42/3456/2304"],
    description: "Venturing into the wild and unknown.",
    price: 64.99,
  },
  {
    id: 14,
    name: "Autumn Serenity",
    image: ["https://picsum.photos/id/43/1280/831"],
    description: "Enjoying the calm of a fall day.",
    price: 49.99,
  },
  {
    id: 15,
    name: "Lakeside Retreat",
    image: ["https://picsum.photos/id/44/4272/2848"],
    description: "Relaxing by the peaceful lakeside.",
    price: 59.99,
  },
  {
    id: 16,
    name: "Sunrise in the Mountains",
    image: ["https://picsum.photos/id/45/4592/2576"],
    description: "Greeting the day from high above.",
    price: 79.99,
  },
  {
    id: 17,
    name: "Urban Skylines",
    image: ["https://picsum.photos/id/46/3264/2448"],
    description: "Capturing the skyline of the city.",
    price: 54.99,
  },
  {
    id: 18,
    name: "Downtown Vibes",
    image: ["https://picsum.photos/id/47/4272/2848"],
    description: "Immersing in the energy of downtown.",
    price: 69.99,
  },
  {
    id: 19,
    name: "Desert Dreams",
    image: ["https://picsum.photos/id/48/5000/3333"],
    description: "Exploring the vast desert landscapes.",
    price: 64.99,
  },
  {
    id: 20,
    name: "Rural Charms",
    image: ["https://picsum.photos/id/49/1280/792"],
    description: "Discovering the charm of rural life.",
    price: 39.99,
  },
  {
    id: 21,
    name: "Coastal Retreat",
    image: ["https://picsum.photos/id/50/4608/3072"],
    description: "A serene escape by the coast.",
    price: 49.99,
  },
  {
    id: 22,
    name: "Mountain Majesty",
    image: ["https://picsum.photos/id/51/5000/3333"],
    description: "Basking in the glory of towering mountains.",
    price: 74.99,
  },
  {
    id: 23,
    name: "City Reflections",
    image: ["https://picsum.photos/id/52/1280/853"],
    description: "Reflecting on the city's beauty.",
    price: 44.99,
  },
  {
    id: 24,
    name: "Nighttime Wonders",
    image: ["https://picsum.photos/id/53/1280/1280"],
    description: "Exploring the magic of the night.",
    price: 59.99,
  },
  {
    id: 25,
    name: "Rustic Landscapes",
    image: ["https://picsum.photos/id/54/3264/2176"],
    description: "Embracing the beauty of rustic scenes.",
    price: 54.99,
  },
  {
    id: 26,
    name: "Coastal Beauty",
    image: ["https://picsum.photos/id/55/4608/3072"],
    description: "Admiring the beauty of the coast.",
    price: 64.99,
  },
  {
    id: 27,
    name: "Nature's Wonders",
    image: ["https://picsum.photos/id/56/2880/1920"],
    description: "Appreciating the wonders of nature.",
    price: 44.99,
  },
  {
    id: 28,
    name: "Mountain Dreams",
    image: ["https://picsum.photos/id/57/2448/3264"],
    description: "Dreaming among the mountain peaks.",
    price: 74.99,
  },
  {
    id: 29,
    name: "Cityscape Elegance",
    image: ["https://picsum.photos/id/58/1280/853"],
    description: "Elegance in the heart of the city.",
    price: 49.99,
  },
  {
    id: 30,
    name: "Tranquil Waters",
    image: ["https://picsum.photos/id/59/2464/1632"],
    description: "Finding tranquility by the waterside.",
    price: 39.99,
  },
];
